(()=> {
const DB='financas_local_v1', STORE='workbook';
const state={data:null,month:null,view:'COMPETENCIA',deferredPrompt:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const monthFmt=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'});
const labels={REMUNERACAO_RAUL:'Remuneração Raul',REMUNERACAO_LETICIA:'Remuneração Letícia',ALUGUEL_RECEBIDO:'Aluguel recebido',CONTRIBUICAO_ESCOLA:'Contribuição escola',MORADIA_ATUAL:'Moradia atual',IMOVEL_ALUGADO:'Imóvel próprio',ALIMENTACAO:'Alimentação',TRANSPORTE:'Transporte',VEICULO:'Veículo',VITOR:'Vitor',SAUDE:'Saúde',PESSOAL_RAUL:'Pessoal Raul',PESSOAL_LETICIA:'Pessoal Letícia',IA_TECNOLOGIA:'IA e tecnologia',ASSINATURAS:'Assinaturas',PRESENTES_EVENTOS:'Presentes e eventos',CASA:'Casa',VIAGEM:'Viagem',DIVIDA_PESSOAL:'Empréstimo pessoal',RESERVA_FAMILIAR:'Reserva familiar',COMPROMISSOS_ANTERIORES:'Parcelas antigas',A_CLASSIFICAR:'A classificar'};
const nonOp=new Set(['TRANSITORIO_TERCEIROS','TRANSFERENCIA_INTERNA','FINANCIAMENTO_RECEBIDO']);
function n(v){if(typeof v==='number')return Number.isFinite(v)?v:0;if(v==null||v==='')return 0;let s=String(v).trim().replace(/R\$/g,'').replace(/\s/g,'');if(/^-?\d+(\.\d+)?$/.test(s))return +s;s=s.replace(/\./g,'').replace(',','.');return Number.isFinite(+s)?+s:0}
function pm(v){if(!v)return null;const s=String(v).trim();if(/^\d{4}-\d{2}$/.test(s))return s;if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,7);const d=new Date(s);return Number.isNaN(d)?null:d.toISOString().slice(0,7)}
function ml(m){if(!m)return '—';const [y,mo]=m.split('-').map(Number);let s=monthFmt.format(new Date(Date.UTC(y,mo-1,1))).replace('.','');return s[0].toUpperCase()+s.slice(1)}
function addM(m,k){const [y,mo]=m.split('-').map(Number),d=new Date(Date.UTC(y,mo-1+k,1));return d.toISOString().slice(0,7)}
function rows(matrix){if(!matrix?.length)return[];const h=matrix[0].map(x=>String(x??'').trim());return matrix.slice(1).filter(r=>r.some(x=>x!==''&&x!=null)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??'']).filter(x=>x[0])))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3000)}
function dbOpen(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbSet(v){const d=await dbOpen();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,'data');tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function dbGet(){const d=await dbOpen();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get('data');r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
async function dbClear(){const d=await dbOpen();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
function workbook(buf,name){if(!window.XLSX)throw Error('Biblioteca XLSX não carregou. Atualize a página e tente novamente.');const wb=XLSX.read(buf,{type:'array',raw:false});const req=['movimentacoes','planejamento','parcelamentos','controle'];const miss=req.filter(x=>!wb.SheetNames.includes(x));if(miss.length)throw Error('Abas ausentes: '+miss.join(', '));const sheets={};wb.SheetNames.forEach(s=>sheets[s]=rows(XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,defval:'',raw:false})));return{fileName:name,importedAt:new Date().toISOString(),sheets}}
function controls(){return Object.fromEntries((state.data?.sheets?.controle||[]).map(r=>[String(r.chave),r.valor]))}
function months(){const s=new Set();(state.data?.sheets?.planejamento||[]).forEach(r=>{const m=pm(r.competencia);if(m)s.add(m)});(state.data?.sheets?.movimentacoes||[]).forEach(r=>{[pm(r.competencia||r.data_transacao),pm(r.data_caixa)].forEach(m=>m&&s.add(m))});return[...s].sort()}
function plan(month=state.month,scenario=null,view=state.view){return(state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===month&&(!scenario||String(r.cenario).toUpperCase()===scenario)&&String(r.visao).toUpperCase()===view)}
function mov(month=state.month,view=state.view){return(state.data?.sheets?.movimentacoes||[]).filter(r=>(view==='CAIXA'?pm(r.data_caixa):pm(r.competencia||r.data_transacao))===month&&String(r.status_movimento||'REALIZADO').toUpperCase()!=='CANCELADO')}
function sum(a,p=()=>true){return a.reduce((x,r)=>x+(p(r)?n(r.valor):0),0)}
function op(r){return !nonOp.has(String(r.grupo||'').toUpperCase())}
function ps(s){const a=plan(state.month,s);const revenue=sum(a,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA');const reserve=Math.abs(sum(a,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR'));const expenses=Math.abs(sum(a,r=>n(r.valor)<0&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR'));return{revenue,expenses,reserve,result:revenue-expenses}}
function rs(){const a=mov().filter(op);const revenue=sum(a,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA');const reserve=Math.abs(sum(a,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR'));const expenses=Math.abs(sum(a,r=>n(r.valor)<0&&String(r.grupo).toUpperCase()!=='RECEITA'&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR'));return{revenue,expenses,reserve,result:revenue-expenses}}
function renderKpis(){const b=ps('BUDGET'),f=ps('FORECAST'),r=rs();const cards=[['Receita forecast',f.revenue,'Budget '+money.format(b.revenue),''],['Despesas forecast',f.expenses,'Budget '+money.format(b.expenses),f.expenses>b.expenses?'bad':''],['Realizado',r.expenses,state.view==='CAIXA'?'Saídas já realizadas':'Consumo já realizado',''],['Reserva prevista',f.reserve,'Aporte planejado','good'],['Resultado forecast',f.result-f.reserve,'Após aporte de reserva',f.result-f.reserve>=0?'good':'bad']];$('#headlineCards').innerHTML=cards.map(([l,v,s,c])=>'<div class="kpi '+c+'"><span class="label">'+l+'</span><div class="value">'+money.format(v)+'</div><div class="sub">'+s+'</div></div>').join('')}
function renderResult(){const b=ps('BUDGET'),f=ps('FORECAST'),r=rs(),vals=[['Budget',b.expenses,''],['Forecast',f.expenses,'forecast'],['Realizado',r.expenses,'realized']],mx=Math.max(...vals.map(x=>x[1]),1);$('#resultChart').innerHTML=vals.map(x=>'<div class="result-row"><span class="name">'+x[0]+'</span><div class="track"><div class="fill '+x[2]+'" style="width:'+Math.min(100,x[1]/mx*100)+'%"></div></div><span class="amount">'+money.format(x[1])+'</span></div>').join('');const d=f.expenses-b.expenses,el=$('#resultBadge');el.textContent=d<=0?'Dentro do Budget':money.format(d)+' acima';el.className='status-pill '+(d<=0?'':d/b.expenses>.05?'bad':'warn')}
function quota(cat,title){const c=controls(),budget=n(c[cat==='PESSOAL_RAUL'?'cota_pessoal_raul':'cota_pessoal_leticia'])||800,real=Math.abs(sum(mov(),r=>op(r)&&String(r.categoria).toUpperCase()===cat&&n(r.valor)<0)),pct=budget?real/budget:0;return '<div class="quota '+(pct>1?'over':'')+'"><div class="quota-top"><span class="quota-name">'+title+'</span><span class="quota-value">'+money.format(real)+' / '+money.format(budget)+'</span></div><div class="track"><div class="fill" style="width:'+Math.min(100,pct*100)+'%"></div></div><div class="quota-note">'+money.format(Math.max(0,budget-real))+' disponíveis</div></div>'}
function renderQuotas(){$('#quotaCards').innerHTML=quota('PESSOAL_RAUL','Raul')+quota('PESSOAL_LETICIA','Letícia')}
function catAgg(){const m=new Map(),add=(c,k,v)=>{if(!c||c==='RESERVA_FAMILIAR')return;if(!m.has(c))m.set(c,{c,b:0,f:0,r:0});m.get(c)[k]+=v};plan(state.month,'BUDGET').forEach(r=>n(r.valor)<0&&add(String(r.categoria).toUpperCase(),'b',Math.abs(n(r.valor))));plan(state.month,'FORECAST').forEach(r=>n(r.valor)<0&&add(String(r.categoria).toUpperCase(),'f',Math.abs(n(r.valor))));mov().filter(op).forEach(r=>n(r.valor)<0&&String(r.grupo).toUpperCase()!=='RECEITA'&&add(String(r.categoria).toUpperCase(),'r',Math.abs(n(r.valor))));return[...m.values()].sort((a,b)=>Math.max(b.b,b.f,b.r)-Math.max(a.b,a.f,a.r))}
function renderCats(){$('#categoryTable').innerHTML=catAgg().map(x=>{const d=x.r-x.b,p=x.b?x.r/x.b:0,st=!x.b?'Sem budget':p<=.9?'Dentro':p<=1?'Atenção':'Acima',cl=p>1?'bad':p>.9?'warn':'';return '<tr><td class="category-name">'+(labels[x.c]||x.c)+'</td><td>'+money.format(x.b)+'</td><td>'+money.format(x.f)+'</td><td>'+money.format(x.r)+'</td><td>'+money.format(d)+'</td><td><span class="status-dot '+cl+'">'+st+'</span></td></tr>'}).join('')||'<tr><td colspan="6">Sem dados neste mês.</td></tr>'}
function installments(m){return(state.data?.sheets?.parcelamentos||[]).reduce((a,r)=>{const st=pm(r.competencia_inicio),en=pm(r.competencia_fim);if(!st||!en||m<st||m>en)return a;return a+Math.abs(n(r.valor_parcela))},0)}
function renderCommit(){const a=Array.from({length:6},(_,i)=>[addM(state.month,i),installments(addM(state.month,i))]),mx=Math.max(...a.map(x=>x[1]),1);$('#commitmentChart').innerHTML=a.map(x=>'<div class="bar-item"><span class="bar-month">'+ml(x[0]).split(' de ')[0]+'</span><div class="track"><div class="fill" style="width:'+x[1]/mx*100+'%"></div></div><span class="bar-value">'+money.format(x[1])+'</span></div>').join('')}
function familyReserve(){return(state.data?.sheets?.patrimonio||[]).reduce((a,r)=>a+(String(r.classe).toUpperCase()==='ATIVO'&&String(r.grupo).toUpperCase()==='RESERVA'?n(r.valor_base):0),0)}
function reserveFor(m){return Math.abs(sum((state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===m&&String(r.cenario).toUpperCase()==='FORECAST'&&String(r.visao).toUpperCase()==='CAIXA'),r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR'))}
function renderReserve(){let c=familyReserve();const pts=[];for(let i=0;i<4;i++){const m=addM(state.month,i);c+=reserveFor(m);pts.push([m,c])}$('#reserveProjection').innerHTML='<div class="reserve-big">'+money.format(c)+'</div><div class="reserve-label">Reserva familiar projetada ao fim de '+ml(pts.at(-1)?.[0]||state.month)+'</div><div class="reserve-timeline">'+pts.map(x=>'<div class="reserve-point"><div class="m">'+ml(x[0])+'</div><div class="v">'+money.format(x[1])+'</div></div>').join('')+'</div>'}
function renderPatrimony(){const a=state.data?.sheets?.patrimonio||[],assets=a.filter(r=>String(r.classe).toUpperCase()==='ATIVO').reduce((x,r)=>x+n(r.valor_base),0),liab=a.filter(r=>String(r.classe).toUpperCase()==='PASSIVO').reduce((x,r)=>x+n(r.valor_base),0),liquid=a.filter(r=>String(r.classe).toUpperCase()==='ATIVO'&&['RESERVA','RESERVA_PESSOAL'].includes(String(r.grupo).toUpperCase())).reduce((x,r)=>x+n(r.valor_base),0);const items=[['Ativos',assets],['Passivos',liab],['Patrimônio líquido',assets-liab],['Liquidez total',liquid]];$('#patrimonyCards').innerHTML=items.map(x=>'<div class="mini-kpi"><div class="label">'+x[0]+'</div><div class="value">'+money.format(x[1])+'</div></div>').join('')}
function renderPending(){const a=state.data?.sheets?.pendencias||[],open=a.filter(r=>['ABERTA','PENDENTE'].includes(String(r.status).toUpperCase())),amt=open.reduce((x,r)=>x+Math.abs(n(r.valor)),0);$('#pendingSummary').innerHTML='<div class="pending-hero"><div><div class="pending-count">'+open.length+'</div><div class="pending-copy">pendências abertas<br>'+money.format(amt)+' sem classificação final</div></div></div><ul class="pending-list">'+open.slice(0,5).map(r=>'<li><span>'+String(r.descricao_original||'—')+'</span><strong>'+money.format(Math.abs(n(r.valor)))+'</strong></li>').join('')+'</ul>'}
function renderForecast(){const a=months().filter(m=>m>=state.month).slice(0,12);$('#forecastTable').innerHTML=a.map(m=>{const rr=(state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===m&&String(r.cenario).toUpperCase()==='FORECAST'&&String(r.visao).toUpperCase()==='CAIXA'),rev=sum(rr,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA'),res=Math.abs(sum(rr,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR')),exp=Math.abs(sum(rr,r=>n(r.valor)<0&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR'));return '<tr><td>'+ml(m)+'</td><td>'+money.format(rev)+'</td><td>'+money.format(exp)+'</td><td>'+money.format(res)+'</td><td>'+money.format(rev-exp)+'</td></tr>'}).join('')||'<tr><td colspan="5">Sem forecast futuro disponível.</td></tr>'}
function meta(){const c=controls(),when=state.data?.importedAt?new Date(state.data.importedAt).toLocaleString('pt-BR'):'—';$('#dataFreshness').textContent='Base '+(c.schema_version||'—')+' • importada '+when;$('#printTitle').textContent=ml(state.month)+' — '+(state.view==='CAIXA'?'Visão de caixa':'Visão de competência');$('#printMeta').textContent=(state.data?.fileName||'Base Mestre')+' • '+when}
function render(){if(!state.data){$('#emptyState').classList.remove('hidden');$('#appShell').classList.add('hidden');return}$('#emptyState').classList.add('hidden');$('#appShell').classList.remove('hidden');renderKpis();renderResult();renderQuotas();renderCats();renderCommit();renderReserve();renderPatrimony();renderPending();renderForecast();meta()}
function populate(){const a=months(),now=new Date().toISOString().slice(0,7);if(!state.month||!a.includes(state.month))state.month=a.includes(now)?now:(a.find(x=>x>now)||a.at(-1));$('#monthSelect').innerHTML=a.map(m=>'<option value="'+m+'" '+(m===state.month?'selected':'')+'>'+ml(m)+'</option>').join('')}
async function importFile(file){try{toast('Importando Base Mestre…');const d=workbook(await file.arrayBuffer(),file.name);await dbSet(d);state.data=d;populate();render();toast('Base atualizada com sucesso.')}catch(e){console.error(e);toast(e.message||'Falha ao importar a planilha.')}}
async function exportPdf(){if(!state.data)return;if(!window.html2canvas||!window.jspdf?.jsPDF){toast('Bibliotecas de PDF ainda não carregaram.');return}const h=$('#printHeader');h.style.display='flex';try{const canvas=await html2canvas($('#snapshot'),{scale:1.35,useCORS:true,backgroundColor:'#fff',windowWidth:1200}),{jsPDF}=window.jspdf,pdf=new jsPDF('p','mm','a4'),W=194,H=canvas.height*194/canvas.width,img=canvas.toDataURL('image/jpeg',.92);let left=H,pos=8;pdf.addImage(img,'JPEG',8,pos,W,H);left-=281;while(left>0){pos=8-(H-left);pdf.addPage();pdf.addImage(img,'JPEG',8,pos,W,H);left-=281}pdf.save('snapshot-financeiro-'+state.month+'-'+state.view.toLowerCase()+'.pdf')}catch(e){console.error(e);toast('Não foi possível gerar o PDF.')}finally{h.style.display=''}}
function bind(){['#fileInput','#fileInputMirror'].forEach(s=>$(s).addEventListener('change',e=>e.target.files?.[0]&&importFile(e.target.files[0])));$('#monthSelect').addEventListener('change',e=>{state.month=e.target.value;render()});$('#viewToggle').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;state.view=b.dataset.view;$$('#viewToggle button').forEach(x=>x.classList.toggle('active',x===b));render()});$('#clearDataBtn').addEventListener('click',async()=>{if(confirm('Remover a cópia local da Base Mestre deste dispositivo?')){await dbClear();state.data=null;render();toast('Dados locais removidos.')}});$('#pdfBtn').addEventListener('click',exportPdf);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('#installBtn').classList.add('hidden')})}
async function init(){bind();try{state.data=await dbGet()}catch(e){}if(state.data)populate();render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
})();