(()=>{
const DB='financas_local_v1',STORE='workbook',THEME='financas_theme';
const state={data:null,month:null,view:'COMPETENCIA',deferredPrompt:null,theme:'light'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),monthFmt=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'});
const labels={REMUNERACAO_RAUL:'Remuneração Raul',REMUNERACAO_LETICIA:'Remuneração Letícia',ALUGUEL_RECEBIDO:'Aluguel recebido',CONTRIBUICAO_ESCOLA:'Contribuição escola',MORADIA_ATUAL:'Moradia atual',IMOVEL_ALUGADO:'Imóvel próprio',ALIMENTACAO:'Alimentação',TRANSPORTE:'Transporte',VEICULO:'Veículo',VITOR:'Vitor',SAUDE:'Saúde',PESSOAL_RAUL:'Pessoal Raul',PESSOAL_LETICIA:'Pessoal Letícia',IA_TECNOLOGIA:'IA e tecnologia',ASSINATURAS:'Assinaturas',PRESENTES_EVENTOS:'Presentes e eventos',CASA:'Casa',VIAGEM:'Viagem',DIVIDA_PESSOAL:'Empréstimo pessoal',DIVIDA_FAMILIAR_ANTERIOR:'Quitação dívida familiar anterior',RESERVA_FAMILIAR:'Reserva familiar',COMPROMISSOS_ANTERIORES:'Parcelas antigas',TERCEIROS_HEITOR:'Heitor / terceiros',A_CLASSIFICAR:'A classificar'};
const nonOp=new Set(['TRANSITORIO_TERCEIROS','TRANSFERENCIA_INTERNA','FINANCIAMENTO_RECEBIDO']);
function n(v){if(typeof v==='number')return Number.isFinite(v)?v:0;if(v==null||v==='')return 0;let s=String(v).trim().replace(/R\$/g,'').replace(/\s/g,'');if(/^-?\d+(\.\d+)?$/.test(s))return+s;s=s.replace(/\./g,'').replace(',','.');return Number.isFinite(+s)?+s:0}
function pm(v){if(!v)return null;const s=String(v).trim();if(/^\d{4}-\d{2}$/.test(s))return s;if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,7);const d=new Date(s);return Number.isNaN(d)?null:d.toISOString().slice(0,7)}
function ml(m){if(!m)return'—';const[y,mo]=m.split('-').map(Number);let s=monthFmt.format(new Date(Date.UTC(y,mo-1,1))).replace('.','');return s[0].toUpperCase()+s.slice(1)}
function addM(m,k){const[y,mo]=m.split('-').map(Number),d=new Date(Date.UTC(y,mo-1+k,1));return d.toISOString().slice(0,7)}
function rows(matrix){if(!matrix?.length)return[];const h=matrix[0].map(x=>String(x??'').trim());return matrix.slice(1).filter(r=>r.some(x=>x!==''&&x!=null)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??'']).filter(x=>x[0])))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3000)}
function dbOpen(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbSet(v){const d=await dbOpen();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,'data');tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function dbGet(){const d=await dbOpen();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get('data');r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
async function dbClear(){const d=await dbOpen();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
function workbook(buf,name){if(!window.XLSX)throw Error('Biblioteca XLSX não carregou. Atualize a página e tente novamente.');const wb=XLSX.read(buf,{type:'array',raw:false}),req=['movimentacoes','planejamento','parcelamentos','controle'],miss=req.filter(x=>!wb.SheetNames.includes(x));if(miss.length)throw Error('Abas ausentes: '+miss.join(', '));const sheets={};wb.SheetNames.forEach(s=>sheets[s]=rows(XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,defval:'',raw:false})));return{fileName:name,importedAt:new Date().toISOString(),sheets}}
function controls(){return Object.fromEntries((state.data?.sheets?.controle||[]).map(r=>[String(r.chave),r.valor]))}
function months(){const s=new Set();(state.data?.sheets?.planejamento||[]).forEach(r=>{const m=pm(r.competencia);if(m)s.add(m)});(state.data?.sheets?.movimentacoes||[]).forEach(r=>{[pm(r.competencia||r.data_transacao),pm(r.data_caixa)].forEach(m=>m&&s.add(m))});return[...s].sort()}
function plan(month=state.month,scenario=null,view=state.view){return(state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===month&&(!scenario||String(r.cenario).toUpperCase()===scenario)&&String(r.visao).toUpperCase()===view)}
function rawMov(month=state.month,view=state.view){return(state.data?.sheets?.movimentacoes||[]).filter(r=>(view==='CAIXA'?pm(r.data_caixa):pm(r.competencia||r.data_transacao))===month&&String(r.status_movimento||'REALIZADO').toUpperCase()!=='CANCELADO')}
function mov(month=state.month,view=state.view){const a=rawMov(month,view);if(view!=='COMPETENCIA')return a;const out=[],seen=new Set();for(const r of a){if(String(r.tipo||'').toUpperCase()==='PARCELA'&&Math.abs(n(r.valor_total_compra))>0){const key=String(r.id_parcelamento||[r.titular,r.data_transacao,r.estabelecimento,r.valor_total_compra,r.parcelas_total].join('|'));if(seen.has(key))continue;seen.add(key);out.push({...r,valor:(n(r.valor)<0?-1:1)*Math.abs(n(r.valor_total_compra))})}else out.push(r)}return out}
function op(r){return!nonOp.has(String(r.grupo||'').toUpperCase())}
function sum(a,p=()=>true){return a.reduce((x,r)=>x+(p(r)?n(r.valor):0),0)}
function ps(s){const a=plan(state.month,s);const revenue=sum(a,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA'),reserve=Math.abs(sum(a,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR')),expenses=Math.abs(sum(a,r=>n(r.valor)<0&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR'));return{revenue,expenses,reserve,result:revenue-expenses}}
function rs(view=state.view){const a=mov(state.month,view).filter(op),revenue=sum(a,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA'),reserve=Math.abs(sum(a,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR')),expenses=Math.abs(sum(a,r=>n(r.valor)<0&&String(r.grupo).toUpperCase()!=='RECEITA'&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR')),unknown=Math.abs(sum(a,r=>String(r.categoria).toUpperCase()==='A_CLASSIFICAR'&&n(r.valor)<0));return{revenue,expenses,reserve,result:revenue-expenses,unknown}}
function installments(m){return(state.data?.sheets?.parcelamentos||[]).reduce((a,r)=>{const st=pm(r.competencia_inicio),en=pm(r.competencia_fim);if(!st||!en||m<st||m>en)return a;return a+Math.abs(n(r.valor_parcela))},0)}
function heitorRows(){return(state.data?.sheets?.parcelamentos||[]).filter(r=>{const isHeitor=String(r.responsavel_terceiro||'').toUpperCase()==='HEITOR'||String(r.categoria||'').toUpperCase()==='TERCEIROS_HEITOR'||String(r.natureza||'').toUpperCase()==='TERCEIRO',en=pm(r.competencia_fim);return isHeitor&&(!en||en>=state.month)}).map(r=>{const total=n(r.numero_parcelas||r.parcelas_total),rest=n(r.parcelas_restantes)||Math.max(0,total-n(r.parcelas_pagas));return{name:r.descricao||r.item||r.descricao_original||'Parcelamento Heitor',value:Math.abs(n(r.valor_parcela)),rest,total,end:pm(r.competencia_fim)}}).sort((a,b)=>b.value-a.value)}
function patrimonySnapshots(){const by=new Map();(state.data?.sheets?.patrimonio||[]).forEach(r=>{const key=pm(r.data_referencia||r.competencia||r.data)||'Atual';if(!by.has(key))by.set(key,{key,assets:0,liab:0,liquid:0,familyReserve:0});const x=by.get(key),cls=String(r.classe||'').toUpperCase(),g=String(r.grupo||'').toUpperCase(),v=n(r.valor_base);if(cls==='ATIVO')x.assets+=v;if(cls==='PASSIVO')x.liab+=v;if(cls==='ATIVO'&&['RESERVA','RESERVA_PESSOAL'].includes(g))x.liquid+=v;if(cls==='ATIVO'&&g==='RESERVA')x.familyReserve+=v});return[...by.values()].map(x=>({...x,net:x.assets-x.liab})).sort((a,b)=>String(a.key).localeCompare(String(b.key)))}
function familyReserve(){return(state.data?.sheets?.patrimonio||[]).reduce((a,r)=>a+(String(r.classe).toUpperCase()==='ATIVO'&&String(r.grupo).toUpperCase()==='RESERVA'?n(r.valor_base):0),0)}
function reserveFor(m){return Math.abs(sum((state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===m&&String(r.cenario).toUpperCase()==='FORECAST'&&String(r.visao).toUpperCase()==='CAIXA'),r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR'))}
function renderKpis(){const b=ps('BUDGET'),f=ps('FORECAST'),r=rs(),has=plan(state.month).length>0,future=[0,1,2].reduce((a,i)=>a+installments(addM(state.month,i)),0);const cards=has?[['Receita forecast',f.revenue,'Budget '+money.format(b.revenue),'neutral'],['Despesas forecast',f.expenses,'Budget '+money.format(b.expenses),f.expenses>b.expenses?'bad':'neutral'],['Despesas realizadas',r.expenses,state.view==='CAIXA'?'Saídas já realizadas':'Consumo já realizado','neutral'],['Superávit antes da reserva',f.result,'Geração operacional do mês',f.result>=0?'good':'bad'],['Reserva prevista',f.reserve,'Saldo após reserva '+money.format(f.result-f.reserve),f.reserve>=b.reserve?'good':'warn']]:[['Receita realizada',r.revenue,'Entradas operacionais do período','neutral'],['Despesas realizadas',r.expenses,state.view==='CAIXA'?'Saídas efetivas do período':'Consumo por competência','neutral'],['Resultado realizado',r.result,'Receitas menos despesas operacionais',r.result>=0?'good':'bad'],['A classificar',r.unknown,'Lançamentos ainda sem classificação final',r.unknown>0?'warn':'good'],['Compromissos futuros',future,'Parcelas ativas nos próximos 3 meses','neutral']];$('#headlineCards').innerHTML=cards.map(([l,v,s,k])=>'<article class="kpi '+k+'"><span class="label">'+l+'</span><div class="value">'+money.format(v)+'</div><div class="sub">'+s+'</div></article>').join('')}
function renderResult(){const b=ps('BUDGET'),f=ps('FORECAST'),r=rs(),has=plan(state.month).length>0,vals=has?[['Budget',b.expenses,''],['Forecast',f.expenses,'forecast'],['Realizado',r.expenses,'realized']]:[['Realizado',r.expenses,'realized']],mx=Math.max(...vals.map(x=>x[1]),1);$('#resultTitle').textContent=has?'Budget × Forecast × Realizado':'Resultado do período';$('#resultChart').innerHTML=vals.map(x=>'<div class="result-row"><span class="name">'+x[0]+'</span><div class="track"><div class="fill '+x[2]+'" style="width:'+Math.min(100,x[1]/mx*100)+'%"></div></div><span class="amount">'+money.format(x[1])+'</span></div>').join('');const el=$('#resultBadge');if(!has||!b.expenses){el.textContent='Sem Budget histórico';el.className='status-pill neutral';return}const d=f.expenses-b.expenses;el.textContent=d<=0?money.format(Math.abs(d))+' abaixo do Budget':money.format(d)+' acima do Budget';el.className='status-pill '+(d<=0?'':d/b.expenses>.05?'bad':'warn')}
function renderBridge(){const comp=rs('COMPETENCIA'),cash=rs('CAIXA'),delta=cash.expenses-comp.expenses,abs=Math.abs(delta),cl=delta>0?'bad':delta<0?'good':'neutral',label=delta>0?'Caixa maior que a competência':delta<0?'Caixa menor que a competência':'Caixa igual à competência';$('#bridgePanel').innerHTML='<div class="bridge-item"><div class="bridge-label">Despesas por competência</div><div class="bridge-value">'+money.format(comp.expenses)+'</div><div class="bridge-copy">Consumo econômico reconhecido no mês, inclusive decisões parceladas pelo valor total da compra.</div></div><div class="bridge-item"><div class="bridge-label">Despesas por caixa</div><div class="bridge-value">'+money.format(cash.expenses)+'</div><div class="bridge-copy">Saídas efetivas do mês: parcelas pagas, datas de fechamento e efeitos de timing.</div></div><div class="bridge-item highlight '+cl+'"><div class="bridge-label">Diferença</div><div class="bridge-value">'+(delta<0?'-':'')+money.format(abs)+'</div><div class="bridge-copy">'+label+'. Essa ponte explica a distância entre comportamento do mês e pressão no caixa.</div></div><div class="bridge-item '+(cash.result>=0?'good':'bad')+'"><div class="bridge-label">Resultado de caixa</div><div class="bridge-value">'+money.format(cash.result)+'</div><div class="bridge-copy">Leitura prática para liquidez e necessidade de reserva.</div></div>'}
function quota(cat,title){const c=controls(),owner=cat==='PESSOAL_RAUL'?'RAUL':'LETICIA',budget=n(c[cat==='PESSOAL_RAUL'?'cota_pessoal_raul':'cota_pessoal_leticia'])||800,explicit=mov().filter(r=>op(r)&&String(r.cota_pessoal||'').toUpperCase()===owner&&n(r.valor)<0),real=Math.abs(explicit.length?sum(explicit):sum(mov(),r=>op(r)&&String(r.categoria).toUpperCase()===cat&&n(r.valor)<0)),pct=budget?real/budget:0;return '<div class="quota '+(pct>1?'over':'')+'"><div class="quota-top"><span class="quota-name">'+title+'</span><span class="quota-value">'+money.format(real)+' / '+money.format(budget)+'</span></div><div class="track"><div class="fill" style="width:'+Math.min(100,pct*100)+'%"></div></div><div class="quota-note">'+(pct<=1?money.format(Math.max(0,budget-real))+' disponíveis':money.format(real-budget)+' acima da cota')+'</div></div>'}
function renderQuotas(){$('#quotaCards').innerHTML=quota('PESSOAL_RAUL','Raul')+quota('PESSOAL_LETICIA','Letícia')}
function catAgg(){const m=new Map(),add=(c,k,v)=>{if(!c||c==='RESERVA_FAMILIAR')return;if(!m.has(c))m.set(c,{c,b:0,f:0,r:0});m.get(c)[k]+=v};plan(state.month,'BUDGET').forEach(r=>n(r.valor)<0&&add(String(r.categoria).toUpperCase(),'b',Math.abs(n(r.valor))));plan(state.month,'FORECAST').forEach(r=>n(r.valor)<0&&add(String(r.categoria).toUpperCase(),'f',Math.abs(n(r.valor))));mov().filter(op).forEach(r=>n(r.valor)<0&&String(r.grupo).toUpperCase()!=='RECEITA'&&add(String(r.categoria).toUpperCase(),'r',Math.abs(n(r.valor))));return[...m.values()].sort((a,b)=>Math.max(b.b,b.f,b.r)-Math.max(a.b,a.f,a.r))}
function renderCats(){const has=plan(state.month).length>0;$('#categoryTitle').textContent=has?'Orçado × realizado':'Categorias realizadas';$('#categoryNote').textContent=has?'Valores de despesa exibidos como positivos para facilitar a leitura.':'Como não há Budget histórico para o mês, a tabela funciona como leitura da composição do realizado.';$('#categoryTable').innerHTML=catAgg().map(x=>{const d=x.r-x.b,p=x.b?x.r/x.b:0,st=!x.b?'Sem budget':p<=.9?'Dentro':p<=1?'Atenção':'Acima',cl=!x.b?'neutral':p>1?'bad':p>.9?'warn':'';return '<tr><td class="category-name">'+(labels[x.c]||x.c)+'</td><td>'+money.format(x.b)+'</td><td>'+money.format(x.f)+'</td><td>'+money.format(x.r)+'</td><td>'+(x.b?(d>0?'+':'')+money.format(d):'—')+'</td><td><span class="status-dot '+cl+'">'+st+'</span></td></tr>'}).join('')||'<tr><td colspan="6">Sem dados neste mês.</td></tr>'}
function renderCommit(){const a=Array.from({length:6},(_,i)=>[addM(state.month,i),installments(addM(state.month,i))]),mx=Math.max(...a.map(x=>x[1]),1);$('#commitmentChart').innerHTML=a.map(x=>'<div class="bar-item"><span class="bar-month">'+ml(x[0]).split(' de ')[0]+'</span><div class="track"><div class="fill" style="width:'+x[1]/mx*100+'%"></div></div><span class="bar-value">'+money.format(x[1])+'</span></div>').join('')}
function renderHeitor(){const a=heitorRows();if(!a.length){$('#heitorPanel').innerHTML='<p class="empty-info">Nenhum parcelamento ativo de Heitor foi identificado na base atual.</p>';return}const open=a.reduce((s,x)=>s+x.rest*x.value,0),next=a.reduce((s,x)=>s+x.value,0);$('#heitorPanel').innerHTML='<div class="heitor-summary"><div class="heitor-kpis"><div class="heitor-mini"><div class="label">Parcelamentos ativos</div><div class="value">'+a.length+'</div></div><div class="heitor-mini"><div class="label">Próxima cobrança</div><div class="value">'+money.format(next)+'</div></div><div class="heitor-mini"><div class="label">Exposição remanescente</div><div class="value">'+money.format(open)+'</div></div></div><ul class="heitor-list">'+a.slice(0,6).map(x=>'<li><div><div class="name">'+x.name+'</div><div class="meta">'+x.rest+' de '+(x.total||'?')+' parcelas restantes · fim '+(x.end?ml(x.end):'—')+'</div></div><div class="value">'+money.format(x.value)+'<br><span class="meta">parcela</span></div></li>').join('')+'</ul></div>'}
function renderReserve(){let c=familyReserve();const pts=[];for(let i=0;i<4;i++){const m=addM(state.month,i);c+=reserveFor(m);pts.push([m,c])}$('#reserveProjection').innerHTML='<div class="reserve-big">'+money.format(c)+'</div><div class="reserve-label">Reserva familiar projetada ao fim de '+ml(pts.at(-1)?.[0]||state.month)+'</div><div class="reserve-timeline">'+pts.map(x=>'<div class="reserve-point"><div class="m">'+ml(x[0])+'</div><div class="v">'+money.format(x[1])+'</div></div>').join('')+'</div>'}
function renderPatrimony(){const s=patrimonySnapshots(),cur=s.at(-1)||{assets:0,liab:0,net:0,liquid:0,familyReserve:0},items=[['Ativos',cur.assets,'Estimativa de mercado / saldo'],['Passivos',cur.liab,'Saldo aproximado das obrigações'],['Patrimônio líquido',cur.net,'Ativos menos passivos'],['Liquidez total',cur.liquid,'Reserva familiar formal: '+money.format(cur.familyReserve||0)]];$('#patrimonyCards').innerHTML=items.map(x=>'<div class="mini-kpi"><div class="label">'+x[0]+'</div><div class="value">'+money.format(x[1])+'</div><div class="note">'+x[2]+'</div></div>').join('');if(s.length<=1){$('#patrimonyEvolution').innerHTML='<div class="evolution-single"><div><div class="title">Snapshot atual</div><div class="value">'+money.format(cur.net)+'</div><div class="note">Ainda temos apenas um ponto histórico. A partir dos próximos fechamentos mensais, a evolução patrimonial aparecerá aqui.</div></div></div>';return}const mx=Math.max(...s.map(x=>Math.max(Math.abs(x.net),1)));$('#patrimonyEvolution').innerHTML='<div class="evolution-head"><div class="title">Patrimônio líquido ao longo do tempo</div><div class="note">'+s.length+' snapshots carregados</div></div><div class="evolution-bars">'+s.map((x,i)=>'<div class="evolution-col '+(i===s.length-1?'current':'')+'"><div class="evolution-track"><div class="evolution-fill" style="height:'+Math.max(10,Math.abs(x.net)/mx*100)+'%"></div></div><div class="evolution-value">'+money.format(x.net)+'</div><div class="evolution-label">'+(x.key==='Atual'?'Atual':ml(x.key))+'</div></div>').join('')+'</div>'}
function renderPending(){const a=state.data?.sheets?.pendencias||[],open=a.filter(r=>['ABERTA','PENDENTE'].includes(String(r.status).toUpperCase())),accepted=a.filter(r=>String(r.status).toUpperCase().includes('ACEITO')),amt=open.reduce((x,r)=>x+Math.abs(n(r.valor)),0);$('#pendingSummary').innerHTML='<div class="pending-hero"><div><div class="pending-count">'+open.length+'</div><div class="pending-copy">pendências abertas<br>'+money.format(amt)+' sem classificação final</div></div><div class="pending-copy">'+accepted.length+' lançamentos mantidos<br>intencionalmente como não classificados</div></div><ul class="pending-list">'+open.slice(0,5).map(r=>'<li><span class="merchant">'+String(r.descricao_original||'—')+'</span><span class="value">'+money.format(Math.abs(n(r.valor)))+'</span></li>').join('')+'</ul>'}
function renderBudget(){const has=plan(state.month).length>0,b=ps('BUDGET'),f=ps('FORECAST'),r=rs();$('#budgetPanelTitle').textContent=has?'Orçamento do mês':'Leitura do histórico';$('#budgetPanelNote').textContent=has?'O orçamento aparece em três camadas: Budget, Forecast e Realizado. A tabela de categorias detalha a composição.':'Para meses históricos sem planejamento formal, o app mostra o realizado e a composição por categoria. O orçamento passa a aparecer nos meses planejados.';if(!has){$('#budgetPanel').innerHTML='<div class="budget-summary"><div class="budget-kpis"><div class="budget-box"><div class="label">Receita realizada</div><div class="value">'+money.format(r.revenue)+'</div><div class="meta">Entradas operacionais</div></div><div class="budget-box"><div class="label">Resultado realizado</div><div class="value">'+money.format(r.result)+'</div><div class="meta">Leitura retrospectiva</div></div></div><p class="empty-info">O orçamento não aparece neste mês porque ele não foi planejado na base. Os meses com Budget completo começam em outubro de 2026.</p></div>';return}$('#budgetPanel').innerHTML='<div class="budget-summary"><div class="budget-kpis"><div class="budget-box"><div class="label">Receita</div><div class="value">'+money.format(f.revenue)+'</div><div class="meta">Budget '+money.format(b.revenue)+'</div></div><div class="budget-box"><div class="label">Despesas</div><div class="value">'+money.format(f.expenses)+'</div><div class="meta">Budget '+money.format(b.expenses)+'</div></div><div class="budget-box"><div class="label">Realizado</div><div class="value">'+money.format(r.expenses)+'</div><div class="meta">'+(state.view==='CAIXA'?'Saídas já realizadas':'Consumo já realizado')+'</div></div><div class="budget-box"><div class="label">Reserva</div><div class="value">'+money.format(f.reserve)+'</div><div class="meta">Superávit '+money.format(f.result)+'</div></div></div><ul class="budget-list"><li><div><div class="name">Saldo após reserva</div><div class="meta">Superávit menos aporte</div></div><div class="value">'+money.format(f.result-f.reserve)+'</div></li><li><div><div class="name">Desvio forecast vs budget</div><div class="meta">Diferença na despesa projetada</div></div><div class="value">'+money.format(f.expenses-b.expenses)+'</div></li><li><div><div class="name">A classificar</div><div class="meta">Lançamentos ainda sem classificação definitiva</div></div><div class="value">'+money.format(r.unknown)+'</div></li></ul></div>'}
function renderForecast(){const a=months().filter(m=>m>=state.month).slice(0,12);$('#forecastTable').innerHTML=a.map(m=>{const rr=(state.data?.sheets?.planejamento||[]).filter(r=>pm(r.competencia)===m&&String(r.cenario).toUpperCase()==='FORECAST'&&String(r.visao).toUpperCase()==='CAIXA'),rev=sum(rr,r=>n(r.valor)>0&&String(r.grupo).toUpperCase()==='RECEITA'),res=Math.abs(sum(rr,r=>String(r.categoria).toUpperCase()==='RESERVA_FAMILIAR')),exp=Math.abs(sum(rr,r=>n(r.valor)<0&&String(r.categoria).toUpperCase()!=='RESERVA_FAMILIAR'));return '<tr><td>'+ml(m)+'</td><td>'+money.format(rev)+'</td><td>'+money.format(exp)+'</td><td>'+money.format(res)+'</td><td>'+money.format(rev-exp)+'</td></tr>'}).join('')||'<tr><td colspan="5">Sem forecast futuro disponível.</td></tr>'}
function meta(){const c=controls(),when=state.data?.importedAt?new Date(state.data.importedAt).toLocaleString('pt-BR'):'—';$('#dataFreshness').textContent='Base '+(c.schema_version||'—')+' • importada '+when;$('#printTitle').textContent=ml(state.month)+' — '+(state.view==='CAIXA'?'Visão de caixa':'Visão de competência');$('#printMeta').textContent=(state.data?.fileName||'Base Mestre')+' • '+when}
function render(){if(!state.data){$('#emptyState').classList.remove('hidden');$('#appShell').classList.add('hidden');return}$('#emptyState').classList.add('hidden');$('#appShell').classList.remove('hidden');renderKpis();renderResult();renderBridge();renderQuotas();renderHeitor();renderCats();renderCommit();renderReserve();renderPatrimony();renderPending();renderBudget();renderForecast();meta()}
function populate(){const a=months(),now=new Date().toISOString().slice(0,7);if(!state.month||!a.includes(state.month))state.month=a.includes(now)?now:(a.find(x=>x>now)||a.at(-1));$('#monthSelect').innerHTML=a.map(m=>'<option value="'+m+'" '+(m===state.month?'selected':'')+'>'+ml(m)+'</option>').join('')}
async function importFile(file){try{toast('Importando Base Mestre…');const d=workbook(await file.arrayBuffer(),file.name);await dbSet(d);state.data=d;populate();render();toast('Base atualizada com sucesso.')}catch(e){console.error(e);toast(e.message||'Falha ao importar a planilha.')}}
async function exportPdf(){if(!state.data)return;if(!window.html2canvas||!window.jspdf?.jsPDF){toast('Bibliotecas de PDF ainda não carregaram.');return}const h=$('.snapshot-header');if(h)h.style.display='flex';try{const canvas=await html2canvas($('#snapshot'),{scale:1.35,useCORS:true,backgroundColor:'#fff',windowWidth:1200}),{jsPDF}=window.jspdf,pdf=new jsPDF('p','mm','a4'),W=194,H=canvas.height*194/canvas.width,img=canvas.toDataURL('image/jpeg',.92);let left=H,pos=8;pdf.addImage(img,'JPEG',8,pos,W,H);left-=281;while(left>0){pos=8-(H-left);pdf.addPage();pdf.addImage(img,'JPEG',8,pos,W,H);left-=281}pdf.save('snapshot-financeiro-'+state.month+'-'+state.view.toLowerCase()+'.pdf')}catch(e){console.error(e);toast('Não foi possível gerar o PDF.')}finally{if(h)h.style.display=''}}
function applyTheme(t){state.theme=t;document.documentElement.setAttribute('data-theme',t);localStorage.setItem(THEME,t);const b=$('#themeToggle');if(b)b.textContent=t==='dark'?'☀︎ Light mode':'☾ Dark mode'}
function bind(){$('#fileInput').addEventListener('change',e=>e.target.files?.[0]&&importFile(e.target.files[0]));$$('.file-input-mirror').forEach(el=>el.addEventListener('change',e=>e.target.files?.[0]&&importFile(e.target.files[0])));$('#monthSelect').addEventListener('change',e=>{state.month=e.target.value;render()});$('#viewToggle').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;state.view=b.dataset.view;$$('#viewToggle button').forEach(x=>x.classList.toggle('active',x===b));render()});$('#clearDataBtn').addEventListener('click',async()=>{if(confirm('Remover a cópia local da Base Mestre deste dispositivo?')){await dbClear();state.data=null;render();toast('Dados locais removidos.')}});$('#pdfBtn').addEventListener('click',exportPdf);$('#themeToggle').addEventListener('click',()=>applyTheme(state.theme==='dark'?'light':'dark'));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('#installBtn').classList.add('hidden')})}
async function init(){const saved=localStorage.getItem(THEME),dark=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;applyTheme(saved||(dark?'dark':'light'));bind();try{state.data=await dbGet()}catch(e){}if(state.data)populate();render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
})();